# Generated by Django 5.2.5 on 2026-06-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custominformationuser",
            name="avatar",
            field=models.ImageField(
                blank=True, default="user/happystick.jpg", null=True, upload_to="user/"
            ),
        ),
    ]
