# Generated by Django 5.2.5 on 2026-06-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="products.order",
            ),
        ),
    ]
